### ISSUE TITLE
Add a limit to the total number of towns per kingdom as a config option

### ISSUE THREAD

**Issue by drewweske** [Rumsfield/konquest#141]
I'm setting up a server for my friends on a very tiny island world, that has a world border of like 200x200. I think that one team could easily just claim literally every available chunk, which would cause a problem when new players are trying to setup a new base but they have no space to. I understand that kingdoms can't spread themselves that thin without being vulnerable to attacks, but I would still like to have land available for people to claim. I also get that this plugin is not meant for such a limited space like this scenario, but it would be cool if this plugin could be used for something like this.

I think, if it's possible, that there should be an option in the config file that determines how many towns a kingdom can have in total. Most likely called something like "MaxTownsPerKingdom". Just like other settings, setting it to 0 would disable any limits, and it is set to zero by default. Setting it to 1 would effectively disable the creation of new towns entirely, as the first one would be taken up by the capital whenever a kingdom is created.
 - Konquest: 1.0.0

**Comment by Rumsfield** [comment]
Thanks for this suggestion, I'll implement it in the next release of Konquest. Here's my plan:

Each kingdom will have a configured limit on the maximum number of towns that its members can settle. This will not affect capturing enemy towns, so a kingdom could still capture all other enemy towns in the server. Captured towns will still contribute to the total town count, so as long as a kingdom controls as many or more towns than the configured maximum limit, then its members cannot settle new towns, only capture enemy ones.

There will also be an extra configuration setting for per-world limits. When `true`, the maximum town limit only applies within a single world. When `false`, the maximum town limit includes all towns in all worlds.
