### ISSUE TITLE
/k menu doesn't work

### ISSUE THREAD

**Issue by 321hackertime** [Rumsfield/konquest#167]
**Bug Description**
> every time i open the /k menu it never lets me click anything

**Steps To Reproduce**
> Steps to reproduce the behavior:
> 1. Log onto server
> 2. use command /k
> 3. click on any option
> 4. does not go to the option or do anything

**Expected Behavior**
> I thought it would bring me to another menu so i could use these commands

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Versions (please complete the following information):**
 - Konquest: 1.20
![konquest help](https://github.com/Rumsfield/konquest/assets/151799272/f8a3c778-41f4-48ee-861e-24012fa1f606)

 - Spigot (put NA if not used): NA
 - Paper (put NA if not used): NA

**Config File(s)**
> https://pastebin.com/k7mKJVbV

**Comment by 321hackertime** [comment]
please ignore my gif being laggy asl obs is just ass on my computer

**Comment by Rumsfield** [comment]
Konquest only supports Spigot/Paper servers. Make sure you are using the latest Paper server version. I have a few questions:
* What version of Minecraft are you using?
* What server software are you using?
* What other plugins are installed on your server?

**Comment by Rumsfield** [comment]
I could not reproduce this bug. Please comment with answers to the questions above and more details if you want to re-open this issue.
