### ISSUE TITLE
Kingdom prevent from breaking any block after leaving the claim.

### ISSUE THREAD

**Issue by VitorDraccon** [Rumsfield/konquest#208]
**Bug Description**
> After Building the Kingdom (For now only on capitals didn't make a town) after getting on the claim is impossible to break any block (can place blocks, can open chests, can open doors, everything but breaking)

**Steps To Reproduce**
> Steps to reproduce the behavior:
> 1. Build a Kingdom
> 2. Make the Capital
> 3. After everything is set, try enter claim and leave.
> 4. after that try breaking block

**Expected Behavior**
> if you're from the kingdom is break

**Versions (please complete the following information):**
 - Konquest: last version
 - Minecraft: 1.20.4

**Comment by Rumsfield** [comment]
Hi, thanks for reporting this. I could not reproduce the issue using Konquest 1.4.1 on a Paper 1.20.4 server. Some suggestions:
* Use the latest Konquest version of 1.4.1.
* Try using the default core.yml settings.
* Make sure you are a resident of the capital or town.
* Make sure you aren't inside of the default world spawn protection area.
* Make sure you aren't inside of the capital's or town's monument chunk.
* Remove any other plugins that may be preventing you from breaking blocks.

If you're still having an issue, please provide more detailed steps on how to reproduce the problem.

**Comment by Rumsfield** [comment]
Closed, could not reproduce.
