### ISSUE TITLE
Konquest 1.4.3 not recognized as the lastest version

### ISSUE THREAD

**Issue by TehebriumDEV** [Rumsfield/konquest#222]
**Bug Description**
>Konquest 1.4.3 is not recognized as the lastest build of Konquest 
It ask me to update to Konquest 1.4.2

![image](https://github.com/Rumsfield/konquest/assets/125908379/40a8a1b4-eb2a-434f-a145-0e4b601807a6)

**Comment by Rumsfield** [comment]
Once a new release version is posted to Spigot MC website, it takes some time to register the new version for the auto-checker in the plugin. By now the version check should be updated to 1.4.3, so I will close this. Please re-open if you still think there's a problem.
