### ISSUE TITLE
health upgrade for towns glitching

### ISSUE THREAD

**Issue by USawesome** [Rumsfield/konquest#253]
**Bug Description**
> After messing around with friends (and buying the health upgrade for my town), I kept getting more and more hearts until I removed the town upgrade. However, I still have these extra hearts, and I can't remove them. I've tried using /attribute, but I don't know the modifier ID that I need to clear the Konquest modifier.

**Steps To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to the town upgrades menu using /k town manage {town name}
> 2. Click on upgrades
> 3. Click on health 1 to purchase the upgrade
> 4. Move in and out of your town border to get more and more max health/hearts

**Expected Behavior**
> The town upgrade should only grant 1 extra heart for level 1, and it should be removed after I exit my town (I believe).

**Screenshots**
> N/A

**Versions (please complete the following information):**
 - Konquest:
 - Spigot: N/A
 - Paper: 1.5.1

**Config File(s)**
[core.yml](https://github.com/user-attachments/files/16183595/core.yml.txt)
[upgrades.yml (is missing health upgrade because I removed it to try and stop this glitch)](https://github.com/user-attachments/files/16183597/upgrades.yml.txt)

**Comment by USawesome** [comment]
## **EDIT:**
> I was able to reset my hp by stopping the server, deleting the playerdata files (in the world folder), and restarting it. However, I would love to use this town upgrade in the future

**Comment by Rumsfield** [comment]
Thanks for reporting this, I'll take a look. The attribute name for the health is [konquest.health_buff](https://github.com/Rumsfield/konquest/blob/main/core/src/main/java/com/github/rumsfield/konquest/Konquest.java#L69)

**Comment by Rumsfield** [comment]
I can't reproduce this on a 1.20.4 Paper server. Which server version are you seeing this problem with? And what other plugins are on your server, maybe one is causing this behavior?

**Comment by USawesome** [comment]
I'm running a 1.21 paper server. I also have AuraSkills installed, which is the only plugin that should modify health, so it may also be the culprit.

**Comment by Rumsfield** [comment]
Thanks for the extra info. I was able to reproduce the problem on a 1.21 server, without AuraSkills. I'll work on fixing this for the next release.
