### ISSUE TITLE
Kingdom Pay issue

### ISSUE THREAD

**Issue by Hailey-Rose** [Rumsfield/konquest#257]
**Bug Description**
> A clear and concise description of what the bug is.
Random Players, throughout The server,in any kingdom, dont get paid the kingdom pay,either at all,or at random times not in line with the config.
**Steps To Reproduce**
> Steps to reproduce the behavior:
>unknown,its seemingly random

**Expected Behavior**
>Players in kingdom should be payed -x- amount every 30 minutes

**Screenshots**
> n/a

**Versions (please complete the following information):**
 - Konquest:1.5.1
 - Spigot (put NA if not used):n/a
 - Paper (put NA if not used):1.20,1
![coreyml](https://github.com/user-attachments/assets/ab2f839c-e91f-490a-9877-d3c029d6a150)

**Config File(s)**
> Attach core.yml (mandatory) and any other relevant config files.

**Comment by Rumsfield** [comment]
Thanks for reporting this, I'll investigate the issue and make a fix in the next release.

**Comment by Rumsfield** [comment]
Just to double check, the expected behavior is for players that meet these requirements will get paid:
* Must be the lord of at least 1 town, OR
* Must be a kingdom officer, OR
* Must be the kingdom master.

Are you seeing players that meet these requirements not getting their kingdom payments?

**Comment by Hailey-Rose** [comment]
oh, i dont think so. sorry. I did read the Wiki Several times, i Guess i misunderstood cause it didnt say it was only those requirements. Is there a way to Change the requirements, or is that not possible?

**Comment by Rumsfield** [comment]
It's not possible to change the requirements for kingdom payments in the plugin configuration. I updated the wiki to be more clear. https://github.com/Rumsfield/konquest/wiki/Kingdoms#payment-requirements
