### ISSUE TITLE
Town watch updates

### ISSUE THREAD

**Issue by USawesome** [Rumsfield/konquest#263]
**Is your feature request related to a problem? Please describe.**
> Town watch, in my opinion is great, but it needs to be updated. Players can purchase it during raids, and there is **no warmup timer** to prevent players from logging out while being raided.

**Describe the solution you'd like**
> It would be great to disable upgrade purchases during raids, and also adding a warmup timer to town watch.

**Additional context**
> None :)

**Version (please complete the following information):**
 - Konquest: 1.5.1

**Comment by Rumsfield** [comment]
I agree that it would be best to always disable new upgrades while a town is under attack, and to add a warmup timer to town watch similar to the offline kingdom protection warmup. I'll work on adding these to the next release. Thanks for your feedback.
